### ISSUE TITLE
How to use Crawl.php it doesn't work i changed the bottom url ??

### ISSUE THREAD

**Issue by ryanjacl** [MusheAbdulHakim/Make-Google-Search-Clone-with-php-and-mysql#1]
I don't know how he input all crawling data.

**Comment by ryanjacl** [comment]
Crawl.php won't work

**Comment by ryanjacl** [comment]
i tried changing url it doesn't work

**Comment by MusheAbdulHakim** [comment]
Can you please screenshot the error that you get when you run crawl.php.

**Comment by ryanjacl** [comment]
Can i ask you a little favour please, as a friend can you make me a php form that users can add url like just <input name=“title> <input name=“ description" manually, not crawling so that I can add important links not just crawling everything

**Comment by MusheAbdulHakim** [comment]
@ryhryan  sorry for the late reply.
I don't really understand what you want. the script is made to crawl all links base on the link that is given in the crawl.php. So if you can give me a little detail of what exactly you. I will work on it. Or you want me to provide a form for the url instead of having to put it in the code?.

**Comment by ryanjacl** [comment]
Ok one last question I need one thing from you, that is how to send reply automatically when someone submit a form in my website like when they enter they’re email and and message automatically reply will send to that email.

**Comment by MusheAbdulHakim** [comment]
@ryhryan that is not actually related to this project right?.
But if you need something like that, you will have to setup the contact form and it's database and query the contact table from the admin side of your website for new enteries. After that, setup an smtp or setup a mailserver to handle sending mails. from there it should be easy to grab the person's email and send them a reply form your side as admin.
Is not really that complex as it may sound.

**Comment by ryanjacl** [comment]
I downloaded oh-mailer I need when my user or anyone input their email on form send auto email to that email please can you make that

**Comment by ryanjacl** [comment]
Sorry it’s phpmailer

**Comment by MusheAbdulHakim** [comment]
yes but you can still use phpmailer it doesn't really matter what you use as far as you know what you are doing.

**Comment by ryanjacl** [comment]
Can you tell me how to take google index and insert to database last help

**Comment by MusheAbdulHakim** [comment]
what do you mean by google index?.

**Comment by ryanjacl** [comment]
I heard on internet lot of search engines use google’s bing’s yandex’’s search result they’re not crawling individually

**Comment by MusheAbdulHakim** [comment]
oh yes. I thought that was what you were talking about but i just wanted to be sure. That is a little bit complicated than what i have here. They have a bot that crawls your website. It is not that simple and it is not something that is you can pick and insert into your database but it also kinda work on the same basic principle. 
When dealing with SEO, you won't be able to see what google or the search engine is doing behind the scenes talkless about inserting their data into your database.
This is just a small project that i wanted to publish and is not quite at the level yet.

**Comment by ryanjacl** [comment]
Can you tell me how to please I’m planing to make this my country’s search engine so I need more data

**Comment by MusheAbdulHakim** [comment]
I see. but this project still needs alot of improvements.
Looking at the way the google index works, is like crawls your webpages and it's contents base on some html tags such as meta tags, hyperlinks and others. so you will have to add more features to the crawler to be able to get these features. I actually wanted to improve this project but i haven't got much time on my hands.

**Comment by ryanjacl** [comment]
If you can add the php files to GitHub I sure would appreciate.

**Comment by MusheAbdulHakim** [comment]
can you please start texting me on hangout this is for issues related to the project

**Comment by ryanjacl** [comment]
I invited you just now

**Comment by ryanjacl** [comment]
Reply me on hangouts, I’m there

**Comment by ryanjacl** [comment]
I sent a invite on hangouts

**Comment by ryanjacl** [comment]
No questions or anythings just can you create me a php form that can insert title url description manually one by one
